### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by Eradev** [Eradev/GridTransitionCrashFix#1]
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Noggog.BinaryMemoryReadStream.ReadUInt16() in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Streams\Binary\BinaryMemoryReadStream.cs:line 151
   at Mutagen.Bethesda.Skyrim.Internals.AVirtualMachineAdapterBinaryCreateTranslation.ReadEntries(MutagenFrame frame, UInt16 objectFormat)+MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Mutagen.Bethesda.Skyrim.Internals.AVirtualMachineAdapterBinaryOverlay.CustomCtor()
   at Mutagen.Bethesda.Skyrim.Internals.AVirtualMachineAdapterBinaryOverlay..ctor(ReadOnlyMemorySlice`1 bytes, BinaryOverlayFactoryPackage package)
   at Mutagen.Bethesda.Skyrim.Internals.QuestAdapterBinaryOverlay..ctor(ReadOnlyMemorySlice`1 bytes, BinaryOverlayFactoryPackage package)
   at Mutagen.Bethesda.Skyrim.Internals.QuestAdapterBinaryOverlay.QuestAdapterFactory(OverlayStream stream, BinaryOverlayFactoryPackage package, Nullable`1 parseParams)
   at Mutagen.Bethesda.Skyrim.Internals.QuestBinaryOverlay.get_VirtualMachineAdapter()
   at Mutagen.Bethesda.Skyrim.Internals.QuestSetterTranslationCommon.DeepCopyIn(IQuest item, IQuestGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.QuestSetterTranslationCommon.DeepCopyIn(IMajorRecord item, IMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Plugins.Records.Internals.MajorRecordSetterTranslationCommon.DeepCopyIn(IMajorRecordInternal item, IMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.SkyrimMajorRecordSetterTranslationCommon.DeepCopyIn(ISkyrimMajorRecordInternal item, ISkyrimMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.QuestSetterTranslationCommon.DeepCopyIn(IQuestInternal item, IQuestGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.QuestSetterTranslationCommon.DeepCopy(IQuestGetter item, TranslationMask copyMask)
   at GridTrasitionCrashFix.Program.RunPatch(IPatcherState`2 state) in C:\Users\admin\AppData\Local\Temp\Synthesis\li5102hz.m3k\Git\tf1dykah.jdz\Runner\GridTrasitionCrashFix\Program.cs:line 23
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 101
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 507
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 428
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 400

**Comment by Eradev** [comment]
Fixed with the updated references.
